language: python

python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "nightly"
 - "pypy"
 - "pypy3"

matrix:
  allow_failures:
    # those "upcoming" python versions are informational
    - python: nightly
    - python: "pypy"
    - python: "pypy3"

sudo: false

addons:
  apt:
    packages:
      - gfortran
      - libfftw3-dev

script:
  ########################################################
  # build
  - make gfortran FFTI=/usr/include
  # install?
  # run example?
  - export OMP_NUM_THREADS=4
  - export PYTHONPATH=":$PWD/../:$PYTHONPATH"
  - python doc/fel-testrun.py
