language: python

python:
 - "2.7"
 - "3.4"
 - "3.5"

sudo: false

before_install:
  # Setup miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  # Create a virtual environment with the right version of python
  - conda create -n testing python=$TRAVIS_PYTHON_VERSION --yes
  - source activate testing

install:
  - conda install --yes scipy h5py

addons:
  apt:
    packages:
      - gfortran
      - libfftw3-dev

script:
  ########################################################
  # build
  - make gfortran FFTI=/usr/include
  # run examples
  - export OMP_NUM_THREADS=4
  - export PYTHONPATH=":$PWD/../:$PYTHONPATH"
  - python doc/tests/run-all-tests.py
